// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/[locale]/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/about">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/accessibility/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/accessibility">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/accessibility/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/ethics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/ethics">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/ethics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/integrations">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/ai-agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/ai-agents">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/ai-agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/algorithms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/algorithms">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/algorithms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/assessments/[id]/conduct/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/assessments/[id]/conduct">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/assessments/[id]/conduct/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/assessments/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/assessments/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/assessments/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/assessments/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/assessments/new">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/assessments/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/assessments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/assessments">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/assessments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/beta-login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/beta-login">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/beta-login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/beta-register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/beta-register">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/beta-register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/careers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/careers">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/careers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/cases/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/cases/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/cases/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/cases/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/cases/new">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/cases/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/cases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/cases">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/cases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/collaborate/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/collaborate/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/collaborate/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/collaborate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/collaborate">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/collaborate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/collaborate/thank-you/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/collaborate/thank-you">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/collaborate/thank-you/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/contact">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/demo/assessment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/demo/assessment">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/demo/assessment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/demo/coding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/demo/coding">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/demo/coding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/demo/ehcp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/demo/ehcp">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/demo/ehcp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/demo/gamification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/demo/gamification">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/demo/gamification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/demo/golden-thread/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/demo/golden-thread">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/demo/golden-thread/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/demo/interventions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/demo/interventions">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/demo/interventions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/demo/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/demo/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/demo/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/demo">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/demo/tracking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/demo/tracking">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/demo/tracking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/demo/training/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/demo/training">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/demo/training/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/demo/translator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/demo/translator">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/demo/translator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/diagnostic/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/diagnostic">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/diagnostic/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/ehcp/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/ehcp/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/ehcp/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/ehcp/modules/annual-reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/ehcp/modules/annual-reviews">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/ehcp/modules/annual-reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/ehcp/modules/compliance-risk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/ehcp/modules/compliance-risk">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/ehcp/modules/compliance-risk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/ehcp/modules/golden-thread/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/ehcp/modules/golden-thread">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/ehcp/modules/golden-thread/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/ehcp/modules/mediation-tribunal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/ehcp/modules/mediation-tribunal">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/ehcp/modules/mediation-tribunal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/ehcp/modules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/ehcp/modules">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/ehcp/modules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/ehcp/modules/phase-transfers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/ehcp/modules/phase-transfers">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/ehcp/modules/phase-transfers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/ehcp/modules/resource-costing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/ehcp/modules/resource-costing">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/ehcp/modules/resource-costing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/ehcp/modules/sen2-returns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/ehcp/modules/sen2-returns">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/ehcp/modules/sen2-returns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/ehcp/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/ehcp/new">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/ehcp/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/ehcp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/ehcp">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/ehcp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/forum/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/forum">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/forum/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/gamification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/gamification">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/gamification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/gdpr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/gdpr">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/gdpr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/help/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/help/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/help/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/help/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/help">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/help/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/institutional-management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/institutional-management">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/institutional-management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/interventions/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/interventions/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/interventions/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/interventions/library/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/interventions/library">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/interventions/library/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/interventions/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/interventions/new">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/interventions/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/interventions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/interventions">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/interventions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/la/applications/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/la/applications/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/la/applications/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/la/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/la/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/la/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/landing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/landing">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/landing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/login">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/marketplace/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/marketplace/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/marketplace/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/marketplace/la-panel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/marketplace/la-panel">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/marketplace/la-panel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/marketplace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/marketplace">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/marketplace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/marketplace/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/marketplace/register">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/marketplace/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/networking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/networking">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/networking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/outcomes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/outcomes">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/outcomes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/parents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/parents">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/parents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/pricing">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/problem-solver/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/problem-solver">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/problem-solver/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/professional/portal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/professional/portal">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/professional/portal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/progress/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/progress">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/progress/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/provision/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/provision">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/provision/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/reports/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/reports/create">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/reports/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/reports">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/research/ethics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/research/ethics">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/research/ethics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/research/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/research">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/research/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/safeguarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/safeguarding">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/safeguarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/school/ehcp-request/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/school/ehcp-request">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/school/ehcp-request/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/senco/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/senco">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/senco/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/signin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/signin">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/signin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/signup">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/subscription/addon/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/subscription/addon">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/subscription/addon/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/subscription/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/subscription">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/subscription/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/teachers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/teachers">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/teachers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/terms">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/test-auth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/test-auth">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/test-auth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/test-login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/test-login">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/test-login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/test-navigation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/test-navigation">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/test-navigation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/tokenisation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/tokenisation">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/tokenisation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/training/certificates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/training/certificates">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/training/certificates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/training/checkout/[productId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/training/checkout/[productId]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/training/checkout/[productId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/training/courses/[id]/learn/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/training/courses/[id]/learn">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/training/courses/[id]/learn/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/training/courses/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/training/courses/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/training/courses/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/training/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/training/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/training/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/training/marketplace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/training/marketplace">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/training/marketplace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/training/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/training">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/training/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/transitions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/transitions">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/transitions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/maintenance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance">> = Specific
  const handler = {} as typeof import("../../src/app/maintenance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/adaptive/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/adaptive">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/adaptive/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/chat">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/demos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/demos">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/demos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/matcher/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/matcher">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/matcher/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/analytics/time-savings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/time-savings">> = Specific
  const handler = {} as typeof import("../../src/app/api/analytics/time-savings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/api-docs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/api-docs">> = Specific
  const handler = {} as typeof import("../../src/app/api/api-docs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assessment/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assessment/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/api/assessment/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assessments/[id]/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assessments/[id]/report">> = Specific
  const handler = {} as typeof import("../../src/app/api/assessments/[id]/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assessments/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assessments/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/assessments/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assessments/collaborations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assessments/collaborations/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/assessments/collaborations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assessments/collaborations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assessments/collaborations">> = Specific
  const handler = {} as typeof import("../../src/app/api/assessments/collaborations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assessments/frameworks/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assessments/frameworks/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/assessments/frameworks/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assessments/instances/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assessments/instances/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/assessments/instances/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assessments/instances/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assessments/instances">> = Specific
  const handler = {} as typeof import("../../src/app/api/assessments/instances/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assessments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assessments">> = Specific
  const handler = {} as typeof import("../../src/app/api/assessments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/forgot-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/forgot-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/refresh">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/session">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signup">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/automation/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/automation/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/api/automation/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/automation/effectiveness/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/automation/effectiveness">> = Specific
  const handler = {} as typeof import("../../src/app/api/automation/effectiveness/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/automation/interventions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/automation/interventions">> = Specific
  const handler = {} as typeof import("../../src/app/api/automation/interventions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/automation/templates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/automation/templates">> = Specific
  const handler = {} as typeof import("../../src/app/api/automation/templates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/battle-royale/match/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/battle-royale/match/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/battle-royale/match/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/battle-royale/matchmaking/queue/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/battle-royale/matchmaking/queue">> = Specific
  const handler = {} as typeof import("../../src/app/api/battle-royale/matchmaking/queue/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/battle-royale/matchmaking/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/battle-royale/matchmaking/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/battle-royale/matchmaking/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/battle-royale/squad/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/battle-royale/squad">> = Specific
  const handler = {} as typeof import("../../src/app/api/battle-royale/squad/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/beta/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/beta/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/beta/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/beta/validate-code/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/beta/validate-code">> = Specific
  const handler = {} as typeof import("../../src/app/api/beta/validate-code/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/blog/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/api/blog/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/blog/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blog/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/blog/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/blog/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blog">> = Specific
  const handler = {} as typeof import("../../src/app/api/blog/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cases/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cases/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/cases/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cases/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cases">> = Specific
  const handler = {} as typeof import("../../src/app/api/cases/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/class/[id]/actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/class/[id]/actions">> = Specific
  const handler = {} as typeof import("../../src/app/api/class/[id]/actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/class/[id]/students/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/class/[id]/students">> = Specific
  const handler = {} as typeof import("../../src/app/api/class/[id]/students/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/class/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/class/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/class/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/coding/curriculum/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/coding/curriculum">> = Specific
  const handler = {} as typeof import("../../src/app/api/coding/curriculum/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/coding/progress/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/coding/progress">> = Specific
  const handler = {} as typeof import("../../src/app/api/coding/progress/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/collaboration/cases/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/collaboration/cases">> = Specific
  const handler = {} as typeof import("../../src/app/api/collaboration/cases/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cpd/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cpd/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/cpd/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cpd/portfolio/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cpd/portfolio">> = Specific
  const handler = {} as typeof import("../../src/app/api/cpd/portfolio/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cpd/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cpd">> = Specific
  const handler = {} as typeof import("../../src/app/api/cpd/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/predictions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/predictions">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/predictions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ehcp/[id]/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ehcp/[id]/export">> = Specific
  const handler = {} as typeof import("../../src/app/api/ehcp/[id]/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ehcp/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ehcp/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/ehcp/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ehcp/annual-reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ehcp/annual-reviews">> = Specific
  const handler = {} as typeof import("../../src/app/api/ehcp/annual-reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ehcp/coherence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ehcp/coherence">> = Specific
  const handler = {} as typeof import("../../src/app/api/ehcp/coherence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ehcp/compliance-risk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ehcp/compliance-risk">> = Specific
  const handler = {} as typeof import("../../src/app/api/ehcp/compliance-risk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ehcp/funding-bands/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ehcp/funding-bands">> = Specific
  const handler = {} as typeof import("../../src/app/api/ehcp/funding-bands/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ehcp/golden-thread/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ehcp/golden-thread">> = Specific
  const handler = {} as typeof import("../../src/app/api/ehcp/golden-thread/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ehcp/mediation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ehcp/mediation">> = Specific
  const handler = {} as typeof import("../../src/app/api/ehcp/mediation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ehcp/phase-transfers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ehcp/phase-transfers">> = Specific
  const handler = {} as typeof import("../../src/app/api/ehcp/phase-transfers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ehcp/provision-costs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ehcp/provision-costs">> = Specific
  const handler = {} as typeof import("../../src/app/api/ehcp/provision-costs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ehcp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ehcp">> = Specific
  const handler = {} as typeof import("../../src/app/api/ehcp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ehcp/sen2-returns/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ehcp/sen2-returns">> = Specific
  const handler = {} as typeof import("../../src/app/api/ehcp/sen2-returns/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ehcp/sen2/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ehcp/sen2/export">> = Specific
  const handler = {} as typeof import("../../src/app/api/ehcp/sen2/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ehcp/sen2/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ehcp/sen2">> = Specific
  const handler = {} as typeof import("../../src/app/api/ehcp/sen2/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ehcp/tribunals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ehcp/tribunals">> = Specific
  const handler = {} as typeof import("../../src/app/api/ehcp/tribunals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/errors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/errors">> = Specific
  const handler = {} as typeof import("../../src/app/api/errors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ethics/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ethics/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/api/ethics/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ethics/assessments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ethics/assessments">> = Specific
  const handler = {} as typeof import("../../src/app/api/ethics/assessments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ethics/incidents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ethics/incidents">> = Specific
  const handler = {} as typeof import("../../src/app/api/ethics/incidents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ethics/monitors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ethics/monitors">> = Specific
  const handler = {} as typeof import("../../src/app/api/ethics/monitors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/feedback">> = Specific
  const handler = {} as typeof import("../../src/app/api/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/forum/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forum/summary">> = Specific
  const handler = {} as typeof import("../../src/app/api/forum/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/gamification/leaderboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gamification/leaderboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/gamification/leaderboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/gamification/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gamification">> = Specific
  const handler = {} as typeof import("../../src/app/api/gamification/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health-dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health-dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/health-dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/help/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/help/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/api/help/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/help/categories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/help/categories">> = Specific
  const handler = {} as typeof import("../../src/app/api/help/categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/help/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/help/chat">> = Specific
  const handler = {} as typeof import("../../src/app/api/help/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/help/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/help">> = Specific
  const handler = {} as typeof import("../../src/app/api/help/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/helpbot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/helpbot">> = Specific
  const handler = {} as typeof import("../../src/app/api/helpbot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integrations/connect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/connect">> = Specific
  const handler = {} as typeof import("../../src/app/api/integrations/connect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integrations/logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/logs">> = Specific
  const handler = {} as typeof import("../../src/app/api/integrations/logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integrations/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/integrations/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/interventions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/interventions/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/interventions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/interventions/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/interventions/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/interventions/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/interventions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/interventions">> = Specific
  const handler = {} as typeof import("../../src/app/api/interventions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/interventions/tracking/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/interventions/tracking">> = Specific
  const handler = {} as typeof import("../../src/app/api/interventions/tracking/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/la/applications/[id]/assign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/la/applications/[id]/assign">> = Specific
  const handler = {} as typeof import("../../src/app/api/la/applications/[id]/assign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/la/applications/[id]/contributions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/la/applications/[id]/contributions">> = Specific
  const handler = {} as typeof import("../../src/app/api/la/applications/[id]/contributions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/la/applications/[id]/decision/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/la/applications/[id]/decision">> = Specific
  const handler = {} as typeof import("../../src/app/api/la/applications/[id]/decision/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/la/applications/[id]/ehcp-draft/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/la/applications/[id]/ehcp-draft">> = Specific
  const handler = {} as typeof import("../../src/app/api/la/applications/[id]/ehcp-draft/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/la/applications/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/la/applications/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/la/applications/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/la/applications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/la/applications">> = Specific
  const handler = {} as typeof import("../../src/app/api/la/applications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/la/compliance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/la/compliance">> = Specific
  const handler = {} as typeof import("../../src/app/api/la/compliance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/la/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/la/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/la/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/learning/personalization/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/learning/personalization">> = Specific
  const handler = {} as typeof import("../../src/app/api/learning/personalization/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/legal/signatures/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/legal/signatures">> = Specific
  const handler = {} as typeof import("../../src/app/api/legal/signatures/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/lessons/assign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lessons/assign">> = Specific
  const handler = {} as typeof import("../../src/app/api/lessons/assign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/lessons/differentiate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lessons/differentiate">> = Specific
  const handler = {} as typeof import("../../src/app/api/lessons/differentiate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/marketplace/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marketplace/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/marketplace/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/marketplace/la-panel/apply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marketplace/la-panel/apply">> = Specific
  const handler = {} as typeof import("../../src/app/api/marketplace/la-panel/apply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/marketplace/professionals/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marketplace/professionals/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/marketplace/professionals/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/marketplace/professionals/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marketplace/professionals/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/marketplace/professionals/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/marketplace/profile/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/marketplace/profile/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/marketplace/profile/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/monitoring/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/monitoring/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/multi-agency/ep-dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/multi-agency/ep-dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/multi-agency/ep-dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/multi-agency/view/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/multi-agency/view">> = Specific
  const handler = {} as typeof import("../../src/app/api/multi-agency/view/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/network/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/network">> = Specific
  const handler = {} as typeof import("../../src/app/api/network/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/onboarding/[...action]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding/[...action]">> = Specific
  const handler = {} as typeof import("../../src/app/api/onboarding/[...action]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orchestrator/agent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orchestrator/agent">> = Specific
  const handler = {} as typeof import("../../src/app/api/orchestrator/agent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orchestrator/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orchestrator/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/orchestrator/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orchestrator/tutor/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orchestrator/tutor">> = Specific
  const handler = {} as typeof import("../../src/app/api/orchestrator/tutor/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/outcomes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/outcomes">> = Specific
  const handler = {} as typeof import("../../src/app/api/outcomes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/outcomes/track/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/outcomes/track">> = Specific
  const handler = {} as typeof import("../../src/app/api/outcomes/track/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/parent/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/parent/messages">> = Specific
  const handler = {} as typeof import("../../src/app/api/parent/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/parent/portal/[childId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/parent/portal/[childId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/parent/portal/[childId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portal/parent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portal/parent">> = Specific
  const handler = {} as typeof import("../../src/app/api/portal/parent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/problem-solver/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/problem-solver">> = Specific
  const handler = {} as typeof import("../../src/app/api/problem-solver/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/professional/contributions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/professional/contributions/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/professional/contributions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/professional/contributions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/professional/contributions">> = Specific
  const handler = {} as typeof import("../../src/app/api/professional/contributions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/professional/development/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/professional/development">> = Specific
  const handler = {} as typeof import("../../src/app/api/professional/development/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/progress/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/progress/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/progress/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/collaborations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/collaborations/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/collaborations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reports/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/reports/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/research/library/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/research/library">> = Specific
  const handler = {} as typeof import("../../src/app/api/research/library/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/resources/library/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/resources/library">> = Specific
  const handler = {} as typeof import("../../src/app/api/resources/library/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/safeguarding/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/safeguarding">> = Specific
  const handler = {} as typeof import("../../src/app/api/safeguarding/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/senco/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/senco">> = Specific
  const handler = {} as typeof import("../../src/app/api/senco/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/settings/integrations/connect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/integrations/connect">> = Specific
  const handler = {} as typeof import("../../src/app/api/settings/integrations/connect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/settings/integrations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/integrations">> = Specific
  const handler = {} as typeof import("../../src/app/api/settings/integrations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/settings/integrations/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/integrations/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/settings/integrations/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/settings/integrations/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/integrations/test">> = Specific
  const handler = {} as typeof import("../../src/app/api/settings/integrations/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/students/[id]/lessons/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/students/[id]/lessons">> = Specific
  const handler = {} as typeof import("../../src/app/api/students/[id]/lessons/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/students/[id]/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/students/[id]/profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/students/[id]/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/students/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/students/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/students/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/students/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/students">> = Specific
  const handler = {} as typeof import("../../src/app/api/students/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/study-buddy/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/study-buddy/chat">> = Specific
  const handler = {} as typeof import("../../src/app/api/study-buddy/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/study-buddy/insights/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/study-buddy/insights">> = Specific
  const handler = {} as typeof import("../../src/app/api/study-buddy/insights/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/study-buddy/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/study-buddy/profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/study-buddy/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/study-buddy/recommendations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/study-buddy/recommendations">> = Specific
  const handler = {} as typeof import("../../src/app/api/study-buddy/recommendations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscription/addon/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscription/addon">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscription/addon/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscription/current/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscription/current">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscription/current/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscription/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscription">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscription/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tokenisation/rewards/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tokenisation/rewards">> = Specific
  const handler = {} as typeof import("../../src/app/api/tokenisation/rewards/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tokenisation/treasury/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tokenisation/treasury">> = Specific
  const handler = {} as typeof import("../../src/app/api/tokenisation/treasury/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/training/courses/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/training/courses/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/training/courses/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/training/courses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/training/courses">> = Specific
  const handler = {} as typeof import("../../src/app/api/training/courses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/training/create-payment-intent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/training/create-payment-intent">> = Specific
  const handler = {} as typeof import("../../src/app/api/training/create-payment-intent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/training/discount-codes/validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/training/discount-codes/validate">> = Specific
  const handler = {} as typeof import("../../src/app/api/training/discount-codes/validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/training/enrollments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/training/enrollments">> = Specific
  const handler = {} as typeof import("../../src/app/api/training/enrollments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/training/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/training/products">> = Specific
  const handler = {} as typeof import("../../src/app/api/training/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/training/progress/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/training/progress">> = Specific
  const handler = {} as typeof import("../../src/app/api/training/progress/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/training/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/training">> = Specific
  const handler = {} as typeof import("../../src/app/api/training/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/transitions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/transitions">> = Specific
  const handler = {} as typeof import("../../src/app/api/transitions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/onboarding/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/onboarding/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/version/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/version">> = Specific
  const handler = {} as typeof import("../../src/app/api/version/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/video/heygen-token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/video/heygen-token">> = Specific
  const handler = {} as typeof import("../../src/app/api/video/heygen-token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/video/heygen-url/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/video/heygen-url">> = Specific
  const handler = {} as typeof import("../../src/app/api/video/heygen-url/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/voice/command/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voice/command">> = Specific
  const handler = {} as typeof import("../../src/app/api/voice/command/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/voice/family/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voice/family">> = Specific
  const handler = {} as typeof import("../../src/app/api/voice/family/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/voice/quick-actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voice/quick-actions">> = Specific
  const handler = {} as typeof import("../../src/app/api/voice/quick-actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/voice/transcribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voice/transcribe">> = Specific
  const handler = {} as typeof import("../../src/app/api/voice/transcribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/waitlist/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/waitlist">> = Specific
  const handler = {} as typeof import("../../src/app/api/waitlist/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/webhooks/stripe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/stripe">> = Specific
  const handler = {} as typeof import("../../src/app/api/webhooks/stripe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/maintenance/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/maintenance">> = Specific
  const handler = {} as typeof import("../../src/app/maintenance/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
