/**
 * Upload All Training Videos to Cloudinary
 * 
 * This script uploads all local training videos to Cloudinary CDN
 * for reliable global distribution.
 * 
 * Prerequisites:
 * - CLOUDINARY_CLOUD_NAME env var
 * - CLOUDINARY_API_KEY env var
 * - CLOUDINARY_API_SECRET env var
 * 
 * Run: npx tsx tools/upload-videos-to-cloudinary.ts
 */

import { v2 as cloudinary } from 'cloudinary';
import * as fs from 'fs';
import * as path from 'path';

// Configure Cloudinary
cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME || 'dncfu2j0r',
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
});

const VIDEO_BASE_PATH = path.join(process.cwd(), 'public', 'content', 'training_videos');
const OUTPUT_FILE = path.join(process.cwd(), 'src', 'lib', 'training', 'cloudinary-video-urls.ts');

interface UploadResult {
  videoKey: string;
  localPath: string;
  cloudinaryUrl: string;
  publicId: string;
  success: boolean;
  error?: string;
}

async function uploadVideo(localPath: string, videoKey: string): Promise<UploadResult> {
  const publicId = `edpsych-connect/videos/${videoKey}`;
  
  try {
    console.log(`  Uploading: ${videoKey}...`);
    
    const result = await cloudinary.uploader.upload(localPath, {
      resource_type: 'video',
      public_id: publicId,
      overwrite: true,
      folder: 'edpsych-connect/videos',
      // Optimisation settings
      eager: [
        { streaming_profile: 'hd', format: 'mp4' },
      ],
      eager_async: true,
    });

    return {
      videoKey,
      localPath,
      cloudinaryUrl: result.secure_url,
      publicId: result.public_id,
      success: true,
    };
  } catch (error) {
    return {
      videoKey,
      localPath,
      cloudinaryUrl: '',
      publicId: '',
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    };
  }
}

function findAllVideos(dir: string, baseKey: string = ''): { key: string; path: string }[] {
  const videos: { key: string; path: string }[] = [];
  
  if (!fs.existsSync(dir)) {
    return videos;
  }

  const entries = fs.readdirSync(dir, { withFileTypes: true });
  
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    
    if (entry.isDirectory()) {
      // Recursively search subdirectories
      const subKey = baseKey ? `${baseKey}/${entry.name}` : entry.name;
      videos.push(...findAllVideos(fullPath, subKey));
    } else if (entry.name.endsWith('.mp4')) {
      // Found a video file
      const videoName = entry.name.replace('.mp4', '');
      const key = baseKey ? `${videoName}` : videoName;
      videos.push({ key, path: fullPath });
    }
  }
  
  return videos;
}

async function main() {
  console.log('🎬 EdPsych Connect - Cloudinary Video Upload\n');
  
  // Check Cloudinary credentials
  if (!process.env.CLOUDINARY_API_KEY || !process.env.CLOUDINARY_API_SECRET) {
    console.error('❌ ERROR: Missing Cloudinary credentials!');
    console.error('   Set CLOUDINARY_API_KEY and CLOUDINARY_API_SECRET environment variables.');
    console.error('\n   Example:');
    console.error('   export CLOUDINARY_API_KEY="your_api_key"');
    console.error('   export CLOUDINARY_API_SECRET="your_api_secret"');
    process.exit(1);
  }

  // Find all video files
  const videos = findAllVideos(VIDEO_BASE_PATH);
  console.log(`📁 Found ${videos.length} video files\n`);

  if (videos.length === 0) {
    console.log('No videos found to upload.');
    return;
  }

  // Upload all videos
  const results: UploadResult[] = [];
  let successCount = 0;
  let failCount = 0;

  for (let i = 0; i < videos.length; i++) {
    const video = videos[i];
    console.log(`[${i + 1}/${videos.length}] ${video.key}`);
    
    const result = await uploadVideo(video.path, video.key);
    results.push(result);
    
    if (result.success) {
      successCount++;
      console.log(`    ✅ ${result.cloudinaryUrl}`);
    } else {
      failCount++;
      console.log(`    ❌ ${result.error}`);
    }

    // Rate limiting - wait 500ms between uploads
    if (i < videos.length - 1) {
      await new Promise(resolve => setTimeout(resolve, 500));
    }
  }

  // Generate TypeScript file with URLs
  const successfulUploads = results.filter(r => r.success);
  
  const tsContent = `/**
 * Cloudinary Video URLs
 * Auto-generated by tools/upload-videos-to-cloudinary.ts
 * Generated: ${new Date().toISOString()}
 * 
 * Total videos: ${successfulUploads.length}
 */

export const CLOUDINARY_VIDEO_URLS: Record<string, string> = {
${successfulUploads.map(r => `  '${r.videoKey}': '${r.cloudinaryUrl}',`).join('\n')}
};

export default CLOUDINARY_VIDEO_URLS;
`;

  fs.writeFileSync(OUTPUT_FILE, tsContent);
  console.log(`\n📄 Generated: ${OUTPUT_FILE}`);

  // Summary
  console.log('\n' + '='.repeat(50));
  console.log('📊 UPLOAD SUMMARY');
  console.log('='.repeat(50));
  console.log(`   Total: ${videos.length}`);
  console.log(`   ✅ Success: ${successCount}`);
  console.log(`   ❌ Failed: ${failCount}`);
  
  if (failCount > 0) {
    console.log('\n⚠️  Failed uploads:');
    results.filter(r => !r.success).forEach(r => {
      console.log(`   - ${r.videoKey}: ${r.error}`);
    });
  }

  console.log('\n✨ Done!');
}

main().catch(console.error);
